package com.project.passmatrixbe;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import com.project.passmatrixbe.User;
import com.project.passmatrixbe.UserRepository;

import javax.validation.constraints.Null;
import java.sql.Blob;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/") // This means URL's start with /demo (after Application path)
@CrossOrigin(origins = "*")
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    
    @GetMapping(path="/getuserimage")
    public @ResponseBody String getUserImage(@RequestParam String username) {
        User user = userRepository.findUserByUsername(username);
        if(user != null) {
            return user.getImagedata();
        } else {
            return null;
        }
    }
    
    @PostMapping(path = "/register")
    public @ResponseBody User registerUser(@RequestBody User user) {
        User newUser = userRepository.save(user);
        return newUser;
    }

    @PostMapping(path = "/login")
    public @ResponseBody Boolean loginUser(@RequestBody User user) {
        String username = user.getUsername();
        String imagedate = user.getImagedata();
        Integer cellId = user.getCellid();
        
        User registeredUser = userRepository.findUserByUsernameAndImagedataAndCellid(username, imagedate, cellId);
        if(registeredUser == null) {
            // Login failed
            return false;
        } 
        // Login success
        return true;
    }
}